# These are supported funding model platforms

github: [millahue]
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift subscription
# custom: # Replace with a custom URL
